name: WaystoneWarps-Pl3xMap
version: ${project.version}
main: org.jamesphbennett.waystonewarps.pl3xmap.WaystonePl3xmapAddon
api-version: '1.21'
author: Hazmad_
description: Pl3xMap integration for WaystoneWarps - Display waystones as toggleable markers on your map

depend:
  - WaystoneWarps
  - Pl3xMap

commands:
  waystones-reload-map:
    description: Manually refresh waystone markers on the map
    usage: /waystones-reload-map
    permission: waystonewarps.pl3xmap.reload
    permission-message: You don't have permission to use this command.

permissions:
  waystonewarps.pl3xmap.reload:
    description: Allows reloading waystone markers on the map
    default: op
